module.exports = [
  {
    id: 1,
    title: 'Piano',
    instructor: 'Miguel',
    date: '25/11',
    time: '20:00',
    image: 'images/piano.png',
  },
  {
    image: 'images/ingles.jfif',
    id: 2,
    title: 'Inglês Básico',
    instructor: 'Luiza',
    date: '04/11',
    time: '14:30',
  },
  {
    image: 'images/libras.jpg',
    id: 3,
    title: 'Libras',
    instructor: 'Helena',
    date: '18/11',
    time: '14:00',
  },
  {
    image: 'images/pintura.jfif',
    id: 4,
    title: 'Pintura',
    instructor: 'Roberto',
    date: '05/12',
    time: '17:30',
  },
  {
    image: 'images/violao.jpg',
    id: 5,
    title: 'Violão',
    instructor: 'Alan',
    date: '10/12',
    time: '12:00',
  },
];
